name: Umbaska_Reloaded
main: uk.co.umbaska.Main
authors: [nfell2009, Gatt, Weefle]
version: 4.0.0
depend: [Skript]
softdepend: [PlotMe, Vault, Towny, NametagEdit, Dynmap, ProtocolLib, WorldEdit, PlotSquared, mcMMO, WorldGuard, Factions, PlaceholderAPI]
loadbefore: [SkQuery]
